package com.expensesTracker.server;

import java.time.LocalDate;
import java.time.LocalTime;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class OpsController {

	@Autowired // This means to get the bean called userRepository
      // Which is auto-generated by Spring, we will use it to handle the data
	private IncomingRepo T1;
	
	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewTransaction (@RequestParam String category
	   , @RequestParam String name, @RequestParam long amt) {
	 // @ResponseBody means the returned String is the response, not a view name
	 // @RequestParam means it is a parameter from the GET or POST request
	
	 IncomingCash n = new IncomingCash(0, name, category, LocalDate.now(), LocalTime.now(), amt);
	 T1.save(n);
	 return "Saved";
	}
	
	@GetMapping(path="/data")
	public @ResponseBody Iterable<IncomingCash> getAllUsers() {
	 // This returns a JSON or XML with the users
	 return T1.findAll();
	}

}




